version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: server
    container_name: eventfy-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/src/db.sqlite3:/app/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventfy-frontend
    ports:
      - 8080:8080
